apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-postgresql-configmap
data:
  DATABASE_URL: "postgresql://clusterip-postgre:5432/apirest?createDatabaseIfNotExist=true&sslmode=disable&useTimezone=true&serverTimezone=UTC"
  USER: "ilab"
  DATABASE: "apirest"
