apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilab-java-jwt-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ilab-java-jwt
  template:
    metadata:
      name: ilab-java-jwt
      labels:
        app: ilab-java-jwt
    spec:
      containers:
        - name: java-jwt
          image: didox/java_jwt:latest
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: remote-postgresql-configmap
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-postgre-secret
                  key: POSTGRE_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: remote-postgresql-configmap
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "3Gi" # 512 MB
              cpu: "1" # 1 milicors VCPU # este recurso tira do meu cluster este recurso #https://www.datacenters.com/news/what-is-a-vcpu-and-how-do-you-calculate-vcpu-to-cpu https://www.hyve.com/what-is-a-vmware-vcpu/
            limits: # caso a aplicação precise de mais recurso, ele coloca este limite automático
              memory: "5Gi" # 800 MB
              cpu: "5"

