apiVersion: v1
kind: Pod
metadata:
  name: ilab-postgre
  labels:
    app: ilab-postgre
spec:
  containers:
    - name: postgresql
      image: postgres
      env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: remote-postgresql-configmap
              key: USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-postgre-secret
              key: POSTGRE_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: remote-postgresql-configmap
              key: DATABASE
      ports:
        - containerPort: 5432
